Repository WeAreBrian/project-fox-poc, pull requests merged in 2023-08, with the labels that each got.

#88 FOX-121: Upgrade build pipeline
  .github/release-drafter.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: skip-changelog

#100 FOX-136-Make-Anchor-Snap-To-Aim-Arrow
  Assets/Scripts/AnchorThrower.cs
Labels: patch

#99 FOX-132: removed tug and stall components
  Assets/Prefabs/PlayerFox.prefab
  Assets/Scripts/AnchorStall.cs
  Assets/Scripts/ChainTugger.cs
Labels: patch

#101 PRE FOX-125: Auto-generated meta files from art assets
  Assets/Animations/SFX animations/Running dust poof.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0000.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0001.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0002.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0003.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0004.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0005.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0006.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0007.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0008.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0009.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0010.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0011.png.meta
  Assets/Animations/SFX animations/Running dust poof/Timeline 1_0012.png.meta
  Assets/Animations/SFX animations/Speed lines.meta
  Assets/Animations/SFX animations/Speed lines/Speed lines 1.png.meta
  Assets/Animations/SFX animations/Speed lines/Speed lines 2.png.meta
  Assets/Animations/SFX animations/Speed lines/Speed lines 3.png.meta
  Assets/Images/Particles.meta
  Assets/Images/Particles/Anchor Impact.png.meta
  Assets/Images/Particles/Breakable rock debris.meta
  Assets/Images/Particles/Breakable rock debris/Breakable rock debris 1.png.meta
  Assets/Images/Particles/Breakable rock debris/Breakable rock debris 2.png.meta
  Assets/Images/Particles/Breakable rock debris/Breakable rock debris 3.png.meta
  Assets/Images/Particles/Breakable rock debris/Breakable rock debris 4.png.meta
  Assets/Images/Particles/Breakable wood debris.meta
  Assets/Images/Particles/Breakable wood debris/Breakable wood debris 1.png.meta
  Assets/Images/Particles/Breakable wood debris/Breakable wood debris 2.png.meta
  Assets/Images/Particles/Breakable wood debris/Breakable wood debris 3.png.meta
  Assets/Images/Particles/Breakable wood debris/Breakable wood debris 4.png.meta
  Assets/Images/Particles/Dust poof.meta
  Assets/Images/Particles/Dust poof/Dust poof 1.png.meta
  Assets/Images/Particles/Dust poof/Dust poof 2.png.meta
  Assets/Images/Particles/Dust poof/Dust poof 3.png.meta
  Assets/Images/Particles/Dust poof/Dust poof 4.png.meta
  Assets/Images/Particles/Glow bug.png.meta
  Assets/Images/Particles/Leaves.meta
  Assets/Images/Particles/Leaves/Leaves 1.png.meta
  Assets/Images/Particles/Leaves/Leaves 2.png.meta
  Assets/Images/Particles/Leaves/Leaves 3.png.meta
  Assets/Images/Particles/Leaves/Leaves 4.png.meta
  Assets/Images/Particles/Leaves/Leaves 5.png.meta
Labels: minor

#102 FOX-146-Honeycomb-Art
  Assets/Images/Interactable.meta
  Assets/Images/Interactable/Grapple honeycomb.meta
  Assets/Images/Interactable/Grapple honeycomb/Grapple honeycomb large.png
  Assets/Images/Interactable/Grapple honeycomb/Grapple honeycomb large.png.meta
  Assets/Images/Interactable/Grapple honeycomb/Grapple honeycomb small.png
  Assets/Images/Interactable/Grapple honeycomb/Grapple honeycomb small.png.meta
Labels: minor

#104 FOX-171-Breakable-Scaffolding-Art
  Assets/Images/Interactable/Breakable scaffolding.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 1.png
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 1.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 2.png
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 2.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 3.png
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 3.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 4.png
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 4.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 5.png
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 5.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 6.png
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 6.png.meta
Labels: minor

#77 Fox-102-Recall-Slingshot
  Assets/Prefabs/PlayerFox.prefab
  Assets/Scenes/Test/Slingshot Test.unity
  Assets/Scenes/Test/Slingshot Test.unity.meta
  Assets/Scripts/Recall.cs
  Assets/Scripts/RecallSlingshot.cs
  Assets/Scripts/RecallSlingshot.cs.meta
Labels: minor

#109 177 breakable wall art
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 1.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 2.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 3.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 4.png
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 4.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 5.png.meta
  Assets/Images/Interactable/Breakable scaffolding/Breakable scaffolding 6.png.meta
  Assets/Images/Particles/Breakable rock debris/Breakable rock debris 1.png.meta
  Assets/Images/Particles/Breakable rock debris/Breakable rock debris 2.png.meta
  Assets/Images/Particles/Breakable rock debris/Breakable rock debris 3.png.meta
  Assets/Images/Particles/Breakable rock debris/Breakable rock debris 4.png.meta
  Assets/Images/Particles/Breakable wood debris/Breakable wood debris 1.png.meta
  Assets/Images/Particles/Breakable wood debris/Breakable wood debris 2.png.meta
  Assets/Images/Particles/Breakable wood debris/Breakable wood debris 3.png.meta
  Assets/Images/Particles/Breakable wood debris/Breakable wood debris 4.png.meta
  Assets/Images/Particles/Dust poof/Dust poof 1.png.meta
  Assets/Images/Particles/Dust poof/Dust poof 2.png.meta
  Assets/Images/Particles/Dust poof/Dust poof 3.png.meta
  Assets/Images/Particles/Dust poof/Dust poof 4.png.meta
  Assets/Materials/Particle materials.meta
  Assets/Materials/Particle materials/Breakable Wood particles.meta
  Assets/Materials/Particle materials/Breakable Wood particles/breakable wood particle 1.mat
  Assets/Materials/Particle materials/Breakable Wood particles/breakable wood particle 1.mat.meta
  Assets/Materials/Particle materials/Breakable Wood particles/breakable wood particle 2.mat
  Assets/Materials/Particle materials/Breakable Wood particles/breakable wood particle 2.mat.meta
  Assets/Materials/Particle materials/Breakable Wood particles/breakable wood particle 3.mat
  Assets/Materials/Particle materials/Breakable Wood particles/breakable wood particle 3.mat.meta
  Assets/Materials/Particle materials/Breakable Wood particles/breakable wood particle.mat
  Assets/Materials/Particle materials/Breakable Wood particles/breakable wood particle.mat.meta
  Assets/Materials/Particle materials/smoke particle.mat
  Assets/Materials/Particle materials/smoke particle.mat.meta
  Assets/Prefabs/HorizontalBreakableWall.prefab
  Assets/Prefabs/RubbleParticle.prefab
  Assets/Prefabs/SmokeParticle.prefab
  Assets/Prefabs/VerticalBreakableWall.prefab
  Assets/Scenes/Levels/Harley Level 1.unity
  Assets/Scripts/BreakableObject.cs
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/TagManager.asset
Labels: minor

#97 Fox 126 convert to 2 d animations
  Assets/Animations/2d fox sprites/Fall.anim
  Assets/Animations/2d fox sprites/Fall.anim.meta
  Assets/Animations/2d fox sprites/FallLeft.anim
  Assets/Animations/2d fox sprites/FallLeft.anim.meta
  Assets/Animations/2d fox sprites/Idle.anim
  Assets/Animations/2d fox sprites/Idle.anim.meta
  Assets/Animations/2d fox sprites/IdleLeft.anim
  Assets/Animations/2d fox sprites/IdleLeft.anim.meta
  Assets/Animations/2d fox sprites/Jump.anim
  Assets/Animations/2d fox sprites/Jump.anim.meta
  Assets/Animations/2d fox sprites/JumpLeft.anim
  Assets/Animations/2d fox sprites/JumpLeft.anim.meta
  Assets/Animations/2d fox sprites/Surf.anim
  Assets/Animations/2d fox sprites/Surf.anim.meta
  Assets/Animations/2d fox sprites/Throw.anim
  Assets/Animations/2d fox sprites/Throw.anim.meta
  Assets/Animations/2d fox sprites/ThrowLeft.anim
  Assets/Animations/2d fox sprites/ThrowLeft.anim.meta
  Assets/Animations/2d fox sprites/WindUp.anim
  Assets/Animations/2d fox sprites/WindUp.anim.meta
  Assets/Animations/2d fox sprites/WindUpLeft.anim
  Assets/Animations/2d fox sprites/WindUpLeft.anim.meta
  Assets/Animations/2d fox sprites/jump sprites.png.meta
  Assets/Animations/2d fox sprites/recall sprites.png.meta
  Assets/Animations/2d fox sprites/run sprites.png.meta
  Assets/Animations/2d fox sprites/surf sprites.png.meta
  Assets/Animations/2d fox sprites/throw sprites.png.meta
  Assets/Animations/FOX SINGULAR FRAME.controller
  Assets/Animations/Run.anim
  Assets/Animations/Run.anim.meta
  Assets/Animations/RunLeft.anim
  Assets/Animations/RunLeft.anim.meta
  Assets/Animations/Square.controller
  Assets/Animations/Square.controller.meta
  Assets/Prefabs/Anchor.prefab
  Assets/Prefabs/PlayerFox.prefab
  Assets/Scenes/Test/Brians Level Idea.unity
  Assets/Scripts/AnchorHolder.cs
  Assets/Scripts/AnchorThrower.cs
  Assets/Scripts/AnimationController.cs
Labels: minor

#106 FOX-125: Speedrun Timer
  Assets/Scenes/Test/Brians Level Idea.unity
  Assets/Scripts/UI/Timer.meta
  Assets/Scripts/UI/Timer/GameTimer.cs
  Assets/Scripts/UI/Timer/GameTimer.cs.meta
  ProjectSettings/TagManager.asset
Labels: minor
